### ISSUE TITLE
can't figure out the equation

### ISSUE THREAD

**Issue by zainasif125** [ricky10116/Python-Crawler--Auto-slide-Douban-verification-ft.-Selenium--OpenCV#1]
can you kindly explain why are you subtracting 76 from the position gotten from the opencv function?

**Comment by ricky10116** [comment]
![image](https://user-images.githubusercontent.com/39448029/193735042-bfb9bf35-e260-426c-9f15-1789deefb31b.png)
If my memory serves me right, the initial button position is not zero, It is 76.
